substitutions:
  _REGION: us-central1
  _CD_PIPELINE: cnat-k8s-cd

steps:
  - name: "google/cloud-sdk:latest"
    entrypoint: "sh"
    args:
      - -xe
      - -c
      - |
        gcloud config set deploy/region ${_REGION}
        sed -i s/PROJECT_ID/$PROJECT_ID/g deploy/*
        gcloud deploy apply --file deploy/pipeline.yaml
        gcloud deploy apply --file deploy/staging.yaml
        gcloud deploy apply --file deploy/prod.yaml
        gcloud deploy releases create rel-${SHORT_SHA} \
                            --delivery-pipeline ${_CD_PIPELINE} \
                            --description "$(git log -1  --pretty='%s')" \
timeout: 3600s
