apiVersion: v1
kind: Service
metadata:
  name: cnat-tracker-service-ip-cluster
  namespace: cnat
spec:
  selector:
    app: cnat-tracker-service
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnat-tracker-service-deployment
  namespace: cnat
  labels:
    app: cnat-tracker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnat-tracker-service
  template:
    metadata:
      labels:
        app: cnat-tracker-service
    spec:
      containers:
      - name: some-cnat-tracker-service
        image: cnat-tracker-service:latest
        imagePullPolicy: Never
        env:
        - name: CNAT_KAFKA_URI
          value: cnat-kafka-ip-cluster:9092
        - name: CNAT_TRACKER_SERVICE_MONGODB_URI
          value: #mongodb://user:pass@host:27017
        ports:
        - containerPort: 80

---
