apiVersion: v1
kind: Service
metadata:
  name: cnat-api-gateway-ip-cluster
  namespace: cnat
spec:
  selector:
    app: cnat-api-gateway
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnat-api-gateway-deployment
  namespace: cnat
  labels:
    app: cnat-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnat-api-gateway
  template:
    metadata:
      labels:
        app: cnat-api-gateway
    spec:
      containers:
      - name: some-cnat-api-gateway
        image: cnat-api-gateway:latest
        imagePullPolicy: Never
        env:
        - name: CNAT_TRACKER_SERVICE_URI
          value: http://cnat-tracker-service-ip-cluster
        - name: CNAT_USER_SERVICE_URI
          value: http://cnat-user-service-ip-cluster
        - name: CNAT_KAFKA_URI
          value: cnat-kafka-ip-cluster:9092
        ports:
        - containerPort: 80

---
