apiVersion: v1
kind: Service
metadata:
  name: cnat-web-app-ip-cluster
  namespace: cnat
spec:
  selector:
    app: cnat-web-app
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnat-web-app-deployment
  namespace: cnat
  labels:
    app: cnat-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnat-web-app
  template:
    metadata:
      labels:
        app: cnat-web-app
    spec:
      containers:
      - name: some-cnat-web-app
        image: cnat-web-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
