---
apiVersion: v1
kind: Service
metadata:
  name: cnat-api-gateway-svc
  namespace: cnat
spec:
  selector:
    app: cnat-api-gateway
  ports:
    - port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnat-api-gateway-deploy
  namespace: cnat
  labels:
    app: cnat-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnat-api-gateway
  template:
    metadata:
      labels:
        app: cnat-api-gateway
    spec:
      containers:
        - name: some-cnat-api-gateway
          image: cnat-api-gateway:latest
          imagePullPolicy: Never
          env:
            - name: CNAT_TRACKER_SERVICE_URI
              value: http://cnat-tracker-service-svc
            - name: CNAT_USER_SERVICE_URI
              value: http://cnat-user-service-svc
            - name: CNAT_WEB_APP_ORIGIN
              value: http://localhost:30080
            - name: CNAT_KAFKA_URI
              value: cnat-kafka-svc:9092
            - name: CNAT_KAFKA_TRACKER_DATA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: cnat-configmap
                  key: cnat_kafka_tracker_data_topic
            - name: CNAT_API_GATEWAY_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cnat-secrets
                  key: cnat-api-gateway_keystore_password
            - name: CNAT_API_GATEWAY_JWT_KEY_ALIAS
              valueFrom:
                secretKeyRef:
                  name: cnat-secrets
                  key: cnat-api-gateway_jwt_key_alias
            - name: CNAT_API_GATEWAY_JWT_KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cnat-secrets
                  key: cnat-api-gateway_jwt_key_password
          ports:
            - containerPort: 80
