apiVersion: v1
kind: Service
metadata:
  name: cnat-kafka-ip-cluster
  namespace: cnat
spec:
  selector:
    app: cnat-kafka
  ports:
  - protocol: TCP
    port: 9092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnat-kafka-deployment
  namespace: cnat
  labels:
    app: cnat-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnat-kafka
  template:
    metadata:
      labels:
        app: cnat-kafka
    spec:
      containers:
      - name: some-cnat-kafka
        image: bitnami/kafka:latest
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: cnat-zookeeper-ip-cluster:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://cnat-kafka-ip-cluster:9092
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
#        - name: BITNAMI_DEBUG
#          value: "true"
        ports:
        - containerPort: 9092

---
