apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cnat-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  # ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: cnat-api-gateway-loadbalancer
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cnat-web-app-nodeport
            port:
              number: 3000
---


apiVersion: v1
kind: Service
metadata:
  name: cnat-web-app-nodeport
spec:
  selector:
    app: cnat-web-app
  ports:
  - protocol: TCP
    port: 3000
---


apiVersion: v1
kind: Service
metadata:
  name: cnat-user-service-nodeport
spec:
  selector:
    app: cnat-user-service
  ports:
  - protocol: TCP
    port: 8082
---


apiVersion: v1
kind: Service
metadata:
  name: cnat-tracker-service-nodeport
spec:
  selector:
    app: cnat-tracker-service
  ports:
  - protocol: TCP
    port: 8081
---


apiVersion: v1
kind: Service
metadata:
  name: cnat-api-gateway-loadbalancer
spec:
  # type: LoadBalancer
  selector:
    app: cnat-api-gateway
  ports:
  - protocol: TCP
    port: 8080
    # targetPort: 8080
    # nodePort: 30080
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnat-web-app-deployment
  labels:
    app: cnat-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnat-web-app
  template:
    metadata:
      labels:
        app: cnat-web-app
    spec:
      containers:
      - name: some-cnat-web-app
        image: cnat-web-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnat-api-gateway-deployment
  labels:
    app: cnat-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnat-api-gateway
  template:
    metadata:
      labels:
        app: cnat-api-gateway
    spec:
      containers:
      - name: some-cnat-api-gateway
        image: cnat-api-gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnat-user-service-deployment
  labels:
    app: cnat-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnat-user-service
  template:
    metadata:
      labels:
        app: cnat-user-service
    spec:
      containers:
      - name: some-cnat-user-service
        image: cnat-user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnat-tracker-service-deployment
  labels:
    app: cnat-tracker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnat-tracker-service
  template:
    metadata:
      labels:
        app: cnat-tracker-service
    spec:
      containers:
      - name: some-cnat-tracker-service
        image: cnat-tracker-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
            
