---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cnat-web-app-hpa
  namespace: cnat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cnat-web-app-deploy
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
