---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cnat-tracker-service-hpa
  namespace: cnat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cnat-tracker-service-deploy
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
