---
apiVersion: v1
kind: Service
metadata:
  name: cnat-kafka-svc
  namespace: cnat
spec:
  selector:
    app: cnat-kafka
  ports:
    - port: 9092
      targetPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnat-kafka-deploy
  namespace: cnat
  labels:
    app: cnat-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnat-kafka
  template:
    metadata:
      labels:
        app: cnat-kafka
    spec:
      containers:
        - name: some-cnat-kafka
          image: bitnami/kafka:latest
          env:
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 1@127.0.0.1:9093
            - name: KAFKA_CFG_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093
            - name: KAFKA_RAFT_CLUSTER_ID
              value: "1"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://cnat-kafka-svc:9092
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            #- name: BITNAMI_DEBUG
            #  value: "true"
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
              ephemeral-storage: 2Gi
            limits:
              memory: 1Gi
              cpu: 250m
              ephemeral-storage: 2Gi
