---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cnat-api-gateway-hpa
  namespace: cnat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cnat-api-gateway-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
